<script>
	import B4 from '../blog/Blog-004.svelte';
</script>

<h1>Disclaimer</h1>
<B4
	blogContent={`Title:About My Art
    Date:2023-jul-24
    42br
    I see art as therapy, both through the use of words and lines. The limitations of language are constricting, but art can act as a safety valve and cure the constipation. It's better than slamming the door, I've found. There's a lot we can't effectively articulate that finds expression in the simplicity, vividness, flexibility, and strangeness that only art can provide—the best tour guide when you're shopping outside the status quo. Those long, muted conversations, the inarticulate madness, the silliness, or some glimpses of the grief I carry are what this blog is trying to capture.
    42br
I don't want to deny the darkness that's inside me anymore. And it's my sincere wish that by screaming the clues and hints about my mental health, I might make a difference to many who don't have a voice and suffer silently. And perhaps in a way, the imperfections that I try to delineate in characters are all part of me; that's how I know they exist, and this negotiated encounter with my fears and fragility may help someone else overcome their demons.
42br
I, for one, don't usually have a future onlooker in mind, except for a future me. I draw because I like to draw. I cherish the "I" part of art, and my unconcern for the "we" insulates me from the emotional afflictions that encumber people who use art to draw attention to themselves.
42br
In any case, I am much better off as a person misunderstood and an invisible, ignored nonentity who aspires to an ambition. Just like my limericks and verse, they're all amateurish gibberish, except that, unlike other polite, conservative people, I'm quite intrepid. On the surface, what might appear to be crass and misanthropic has a deeper groove. The pain in my life as told by a contrarian and an iconoclast is still an oversimplification of what is going on in my head, but at least it's the beginning of a conversation. And like William Blake, I'll go unnoticed until much later, when historians will start examining the discarded fossils with an investigative lens. But again, it doesn't matter.
42br
I know that the content isn't politically correct. I've always had an issue with being family-friendly, or with euphemisms. You can't please everyone. There are far too many egos in the world. There's always someone wanting to bloody your nose over something, no matter how soft your language. It's easier on them when I get into a character. An insult from a salacious cartoon distraction isn't that corrosive, especially if you can't think. People struggle incessantly with the truth, boxed in their views by the pastry layers of deceptions and delusions—the sociopolitical and religious, the economic, and most importantly, the moral. I'm quite sure they have naturally reserved their love for mealy-mouthed, spineless pleasers and would harbor large dollops of ill will against me. They'd rather be in the dark than put up with the light. Light has the irritating habit of exfoliating assumptions and revealing stark realities.
42br
But unfortunately, it's blood loss in vain. The world has become so incongruous that even the harshest, luridest, satirical exaggeration of it fails to deliver the bitter irony of the reality I see around me. And people are so resistant to the truth that a comical inversion only serves to elicit a superficial, obvious reaction, thus failing to deliver the punch. In effect, cringe stays cringe, unable to deliver the payload because that requires a thinking mind, perhaps one that's a little bit mad.
42br
Although some of the material in these posts is part of my extended inner monologue, there's no clear derivation of the deviant emotion, an autobiographical reveal, or a bona fide sketch of the repressed feeling. Maybe in a very generous compartmentalized way, like the level of trapped mercury in a vessel. It could be measuring various things, and you wouldn't be able to tell "what" if the labels on the unit went missing. When I draw a grotesque face, it may be an indication of my emotions, but it's not connected in a meaningful way, and taking it literally at face value and making a judgment would be silly. If we can't laugh at our own confabulations, then we risk misunderstanding our own place in the universe and starting to take things too seriously. And it may hurt our anthropocentric ego, but putting human faces on animals can have lurid results, I've noticed.
42br
I often use the expectation of revulsion as a way to distinguish myself from just another pastiche. It's an internal assessment foisted on an imaginary critic and not a good justification for the darkness. But when you describe the darkness, it's no longer dark.
42br
The worthiness of art is a matter of consensus, usually and historically, something that the artist hasn't profited from because that appraisal frequently happens posthumously. More than the art, it's the quality of uproar that you are able to generate, or more appropriately these days, fund, that determines whether an artist, in his lifetime, is able to climb out of obscurity. Distance in time or space, as an amplifier enhances, often adds an element of mystery. If anyone pays attention, these are often grafts to bolster missing information. Also, when you're dead, whatever you are can be flexibly redefined to suit the fancy of the benefactor. You can't protest. Thus, a caveman struggling with his art may be in the news for etching an alien.
42br
And the reason is not so much that we don't care but, more pertinently, that we aren't quite sure if what we think in our heads is really all that. Consensus, however you manage it, gives you the statistically kosher answer. The first one to complement something ill-defined could make you the black sheep of the flock. What dark meanings or ulterior motives lurk behind the patina of lust isn't always clear. When we see something that doesn't immediately make sense to us, being the practical people that we are, we immediately dismiss it. No one in Van Gogh's time believed his art amounted to much. And he constantly struggled with poverty.
42br
You can often have majestic masts but get nowhere. Mine is such a ship. I've hit the doldrums, and without a wind beneath my sails, I'm as good as rotting. Incidentally, it seems I have a knack for driving into the doldrums.
42br
And art, for me, is sort of an expression of a compulsive tic—a compulsion to exfoliate what's beneath all the makeup. It's often whatever is itching my curiosity. It's something I have to force out of my head or risk a rattle or jingle that's difficult to cure. I just start a doodle and keep at it until I want to do something else. It's that simple. I'm not an artist by any stretch of the imagination. I don't make a living off of it. It's just a tic that helps explore the ingredients in the constituent wandering thoughts, the mysterious vagabonds that visit my mind to console the otherwise lonely, barren, and empty landscape.
42br
These are thought experiments that usually deal with the unpleasant and the unremarkable. It helps to distance myself from me, find the brakes, attenuate, and soothe. Perhaps the art is the curated fulmination of a closet thinker presented as is. Filaments of figment, visualized babble, and fiction concocted, And sometimes stranger than that. Or a discolored montage of what my life has been.
42br
And that is why I can't put labels on them with an intellectual identification of what their meaning is without over-analyzing them to shreds. Sometimes I do, and then it's just a post-hoc postmortem of something that wasn't really behind the inspiration. Most of the labels do have a post and a title on them that express, as the case may be, a need of the moment, although it's not always causal by creation. Or sometimes they are, but I'd be wary if you attach too much attention to such things. `}
image_name ="me.webp"
/>
